# Generated by Django 2.1.5 on 2019-01-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partipant_id', models.IntegerField(max_length=30, unique=True)),
            ],
        ),
    ]
