# Generated by Django 2.1.5 on 2019-01-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='partipant_id',
            field=models.IntegerField(unique=True),
        ),
    ]
