# Generated by Django 2.1.5 on 2019-01-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20190109_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField(unique=True)),
                ('datetime_attendance_logged', models.DateTimeField()),
                ('time_of_day', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Evening')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='barcode',
            field=models.IntegerField(default=1234567890, unique=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
