# Generated by Django 2.1.5 on 2019-01-09 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20190109_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='partipant_id',
            new_name='participant_id',
        ),
    ]
