# Generated by Django 2.1.5 on 2019-01-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20190125_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
